### ISSUE TITLE
require module is crashing 

### ISSUE THREAD

**Issue by bang** [aharb/SecUtil#1]
Hi!

This error at bellow appears when I try to require secutil module:

C:\Users\SOMEUSER\Working\EmotionWebSQL\api\node_modules\secutil\lib\logging.js:1
(function (exports, require, module, __filename, __dirname) { module.exports = require('logging').from(__filename);
                                                                                                  ^

TypeError: require(...).from is not a function
    at Object.<anonymous> (C:\Users\SOMEUSER\Working\EmotionWebSQL\api\node_modules\secutil\lib\logging.js:1:99)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\SOMEUSER\Working\EmotionWebSQL\api\node_modules\secutil\index.js:2:13)
    at Module._compile (module.js:571:32)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by whitehorse5353** [comment]
same with me :(
